### ISSUE TITLE
File format and using with MIMIC-III

### ISSUE THREAD

**Issue by isaacmg** [mp2893/mime#1]
Hi I really enjoyed your paper and  I was wondering if you had an example of the files you used or how to apply this code on MIMIC. 

Thanks.

**Comment by mp2893** [comment]
Hi, isaacmg 

Thank you for taking interest in the paper.
As you could guess, I can't share the dataset I used in the paper since they are Sutter Health's property.
And, unfortunately, MIMIC3 doesn't provide the link information between a diagnosis and the medication/procedure orders caused by the diagnosis. (I'm not sure if there are any publicly available electronic health records that contain such link information)
But you could artificially generate those link information from external knowledge, (e.g. we know that acetaminophen is ordered for fever or headaches) if you are keen on trying out MiME on MIMIC3.

Thanks,
Ed

ps. BTW, the current MiME repo page severely lacks information. I'll try update the page soon (can't guaranee when though)

**Comment by isaacmg** [comment]
Thanks for your response. I definitely understand the HIPPA issue. When you do update it could you include information about preprocessing and the general schema of the files (without revealing any PHI)? As that will definitely help get a better sense of what records are needed.

Thanks again.

**Comment by mp2893** [comment]
Absolutely, will do!
